openapi: 3.0.0
info:
  title: Todo List API
  version: 1.0.0
  description: API for managing todo items
servers:
  - url: http://localhost:3001
    description: Development server
paths:
  /todo/all:
    get:
      summary: Get all todos
      responses:
        '200':
          description: A list of todos
  /todo/complete/{id}:
    get:
      summary: Get a todo by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single todo item
  /todo/add:
    post:
      summary: Add a new todo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                priority:
                  type: string
                category:
                  type: string
      responses:
        '201':
          description: Todo created successfully
  /todo/delete/{id}:
    delete:
      summary: Delete a todo by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Todo deleted successfully
  /todo/update/{id}:
    put:
      summary: Update a todo by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                priority:
                  type: string
                category:
                  type: string
      responses:
        '200':
          description: Todo updated successfully